version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run FindBugs
          command: ./gradlew findbugs
      - run:
          name: Run Pmd
          command: ./gradlew pmd
      - run:
          name: Run Lint
          command: ./gradlew lintRelease
      - run:
          name: Run Tests
          command: ./gradlew testDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
